apiVersion: iter8.tools/v2alpha1
kind: Metric
metadata:
  name: request-count
spec:
  params:
    query: sum(increase(revision_app_request_latencies_count{service_name=~'.*$name'}[$interval])) or on() vector(0)
  description: Number of requests
  type: counter
  provider: prometheus
---
apiVersion: iter8.tools/v2alpha1
kind: Metric
metadata:
  name: mean-latency
spec:
  description: Mean latency
  units: milliseconds
  params:
    query: (sum(increase(revision_app_request_latencies_sum{service_name=~'.*$name'}[$interval]))or on() vector(0)) / (sum(increase(revision_app_request_latencies_count{service_name=~'.*$name'}[$interval])) or on() vector(0))
  type: gauge
  sample_size: 
    name: request-count
  provider: prometheus
---
apiVersion: iter8.tools/v2alpha1
kind: Metric
metadata:
  name: 95th-percentile-tail-latency
spec:
  description: 95th percentile tail latency
  units: milliseconds
  params:
    query: histogram_quantile(0.95, sum(rate(revision_app_request_latencies_bucket{service_name=~'.*$name'}[$interval]))
      by (le))
  type: gauge
  sample_size: 
    name: request-count
  provider: prometheus
---
apiVersion: iter8.tools/v2alpha1
kind: Metric
metadata:
  name: error-count
spec:
  description: Number of error responses
  params:
    query: sum(increase(revision_app_request_latencies_count{response_code_class!='2xx',service_name=~'.*$name'}[$interval])) or on() vector(0)
  type: counter
  provider: prometheus
---
apiVersion: iter8.tools/v2alpha1
kind: Metric
metadata:
  name: error-rate
spec:
  description: Fraction of requests with error responses
  params:
    query: (sum(increase(revision_app_request_latencies_count{response_code_class!='2xx',service_name=~'.*$name'}[$interval])) or on() vector(0)) / (sum(increase(revision_app_request_latencies_count{service_name=~'.*$name'}[$interval])) or on() vector(0))
  type: gauge
  sample_size: 
    name: request-count
  provider: prometheus
    
